apiVersion: v1
entries:
  ocpp:
  - apiVersion: v2
    appVersion: 0.0.72-dev
    created: "2021-09-03T21:59:34.031795244Z"
    description: A Helm chart for Kubernetes
    digest: 82ef3c2894c643faada4a81e739416d8f41b002b50bdb0bb904f9e5a544d82ff
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/emaps-apps-helm/main/charts/ocpp-0.0.72-dev.tgz
    version: 0.0.72-dev
  - apiVersion: v2
    appVersion: 0.0.70-dev
    created: "2021-09-03T21:15:47.223076296Z"
    description: A Helm chart for Kubernetes
    digest: 7c261acccc1b65190b00634d4d46690dcd7ff319d1609ad8582006908764dae4
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/emaps-apps-helm/main/charts/ocpp-0.0.70-dev.tgz
    version: 0.0.70-dev
  - apiVersion: v2
    appVersion: 0.0.22
    created: "2021-09-03T17:20:15.039423343Z"
    description: A Helm chart for Kubernetes
    digest: 3365ba415f38dcb48f8d5957386b3c25a8095c4aa93643839741624e5d1216e8
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/emaps-apps-helm/main/charts/ocpp-0.0.22.tgz
    version: 0.0.22
  - apiVersion: v2
    appVersion: 0.0.21
    created: "2021-09-01T16:40:49.351355149Z"
    description: A Helm chart for Kubernetes
    digest: 264fe677c71f872c37fca9902036303b111f785915c9f6fdf010c353d03c4b84
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/emaps-apps-helm/main/charts/ocpp-0.0.21.tgz
    version: 0.0.21
  - apiVersion: v2
    appVersion: 0.0.19
    created: "2021-09-01T12:34:40.645785769Z"
    description: A Helm chart for Kubernetes
    digest: e26ee4b8c0d7eb6f2e6642e729ff62917f6bcb8934f71823dad94c746273ba5c
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.19.tgz
    version: 0.0.19
  - apiVersion: v2
    appVersion: 0.0.18
    created: "2021-08-28T23:04:26.133842916Z"
    description: A Helm chart for Kubernetes
    digest: 9960a0a0ca58c8db10368020feccc08ed90f22df191051f80030231c3f6b7106
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.18.tgz
    version: 0.0.18
  - apiVersion: v2
    appVersion: 0.0.17
    created: "2021-08-28T21:45:07.931525933Z"
    description: A Helm chart for Kubernetes
    digest: 23ee495d7ca34b7b319fdcca6668a02340a16a74da7afe50c54c7bd1b2d9bb34
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.17.tgz
    version: 0.0.17
  - apiVersion: v2
    appVersion: 0.0.16
    created: "2021-08-28T21:19:31.819452054Z"
    description: A Helm chart for Kubernetes
    digest: 5f1b0d158cfaf295d445fef908b5f2120cffb3f2be76f2f01c412e22c1269145
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.16.tgz
    version: 0.0.16
  - apiVersion: v2
    appVersion: 0.0.15
    created: "2021-08-28T20:37:49.540034672Z"
    description: A Helm chart for Kubernetes
    digest: 2e2a1f217b2465a4a42c3f5d963fc6041591e5ef75dcc179166e9a2a60d8b137
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.15.tgz
    version: 0.0.15
  - apiVersion: v2
    appVersion: _VERSION_RELEASE_
    created: "2021-08-28T20:23:45.773677459Z"
    description: A Helm chart for Kubernetes
    digest: ffe5398c0810b6de8a77bb929d7efc235b43df729adbe07bb42ed93c8c613d18
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.14.tgz
    version: 0.0.14
  - apiVersion: v2
    appVersion: _VERSION_RELEASE_
    created: "2021-08-28T19:13:30.321487982Z"
    description: A Helm chart for Kubernetes
    digest: 4388cbefda4def466a7f3dd57880be4bab17a74c2003b062c7fc2e119d0a75d0
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.13.tgz
    version: 0.0.13
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-08-28T18:09:04.46521136Z"
    description: A Helm chart for Kubernetes
    digest: 967fbb48c00719dcb5360ea2430ea0d0d66f942b0889e810aa7326f94d212d9d
    name: ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/test-helm/master/charts/ocpp-0.0.12.tgz
    version: 0.0.12
  - apiVersion: v2
    appVersion: 0.0.0-5535a0d-dev
    created: "2021-09-03T19:19:09.736178537Z"
    description: A Helm chart for Kubernetes
    digest: 69ba0b58b9ad3cf30787f0647e43e7d9a9626c71e08a9099ef82492502b181c3
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/emaps-apps-helm/main/charts/ocpp-0.0.0-5535a0d-dev.tgz
    version: 0.0.0-5535a0d-dev
  - apiVersion: v2
    appVersion: 0.0.0-1199395723-dev
    created: "2021-09-03T21:05:17.636169492Z"
    description: A Helm chart for Kubernetes
    digest: d2babf8943ef251e91c21eead005c0cdb7bbdc4ba2d22d18e21bccf88e9c8d85
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/emaps-apps-helm/main/charts/ocpp-0.0.0-1199395723-dev.tgz
    version: 0.0.0-1199395723-dev
  - apiVersion: v2
    appVersion: 0.0.0--dev
    created: "2021-09-03T20:54:23.74888053Z"
    description: A Helm chart for Kubernetes
    digest: 89ac75f03478bfea5071668c5d50d221871ca6f336684b17e4a6933dbf783e07
    home: https://github.com/ElectromapsSL/ocpp
    icon: https://pbs.twimg.com/profile_images/1346477894533464066/C8gEbxou.png
    name: ocpp
    sources:
    - https://github.com/ElectromapsSL/ocpp
    type: application
    urls:
    - https://raw.githubusercontent.com/Cosmic-Chimps/emaps-apps-helm/main/charts/ocpp-0.0.0--dev.tgz
    version: 0.0.0--dev
generated: "2021-09-03T21:59:34.031247441Z"
